// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

error Arcadia__ZeroAddress();
error Arcadia__ZeroAmount();
error Arcadia__Unauthorized(bytes32 role, address account);
error Arcadia__RoleAlreadyGranted(bytes32 role, address account);
error Arcadia__RoleNotGranted(bytes32 role, address account);
error Arcadia__InvalidRoleAdmin(bytes32 role, bytes32 adminRole);
error Arcadia__InvalidTranche(uint8 tranche);
error Arcadia__InvalidFee(uint256 feeBps);
error Arcadia__InvalidBps(uint256 bps);
error Arcadia__DepositsPaused();
error Arcadia__RedemptionsPaused();
error Arcadia__HarvestPaused();
error Arcadia__EmergencyModeActive();
error Arcadia__EmergencyModeInactive();
error Arcadia__TrancheDepositsDisabled(uint8 tranche);
error Arcadia__TrancheRedemptionsDisabled(uint8 tranche);
error Arcadia__InsufficientShares(uint256 requested, uint256 available);
error Arcadia__InsufficientAssets(uint256 requested, uint256 available);
error Arcadia__InsufficientLiquidity(uint256 requested, uint256 available);
error Arcadia__InsufficientAllowance(uint256 requested, uint256 available);
error Arcadia__UnsupportedTokenBehavior();
error Arcadia__ShareAmountZero();
error Arcadia__AssetAmountZero();
error Arcadia__DepositCapExceeded(uint8 tranche, uint256 resultingAssets, uint256 cap);
error Arcadia__LossReportPending(uint256 reportId);
error Arcadia__LossReportNotPending(uint256 reportId);
error Arcadia__LossReportNotFound(uint256 reportId);
error Arcadia__LossExceedsAssets(uint256 lossAmount, uint256 totalAssets);
error Arcadia__LossExceedsLiquidity(uint256 lossAmount, uint256 liquidAssets);
error Arcadia__CannotCancelSettledReport(uint256 reportId);
error Arcadia__Reentrancy();
error Arcadia__TokenNotRecoverable(address token);
error Arcadia__InvalidStrategy(address strategy);
error Arcadia__StrategyAlreadyListed(address strategy);
error Arcadia__StrategyNotActive(address strategy);
error Arcadia__StrategyDebtLimitExceeded(address strategy, uint256 resultingDebt, uint256 limit);
error Arcadia__StrategyReportStale(address strategy, uint256 lastReport, uint256 staleAfter);
error Arcadia__PriceConfidenceLow(uint256 observedBps, uint256 requiredBps);
error Arcadia__RiskBandInactive(uint8 tranche);
error Arcadia__TransferFailed();
error Arcadia__LimitExceeded(uint256 requested, uint256 limit);
error Arcadia__ValueOverflow(uint256 value);
error Arcadia__RequestNotReady(uint256 requestId, uint256 executableAt);
error Arcadia__MinimumAssetsNotMet(uint256 observed, uint256 minimum);
error Arcadia__CheckpointMismatch(bytes32 expected, bytes32 observed);
